apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditrack-api
  namespace: meditrack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meditrack-api
  template:
    metadata:
      labels:
        app: meditrack-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: meditrack-api
          image: tosinseni255/meditrack-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: meditrack-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5