apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meditrack-monitor
  namespace: meditrack
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: meditrack-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s