apiVersion: v1
kind: Service
metadata:
  name: meditrack-service
  namespace: meditrack
  labels:
    app: meditrack-api
spec:
  type: LoadBalancer
  selector:
    app: meditrack-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000